openapi: 3.0.3
info:
  title: test
  version: 1.0.0

paths:
  /test:
    get:
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UsedAllOf'

components:
  schemas:
    UsedAllOf:
      type: object
      allOf:
        - $ref: '#/components/schemas/Model'

    Model:
      type: object
      properties:
        test:
          type: string
